name: CI

on: [push, pull_request]

jobs:
  ruby_rails_matrix:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        ruby: [2.4, 2.7, 3.0]
        rails: [4, 5, 6]
        exclude:
          - ruby: 2.4
            rails: 6
          - ruby: 2.7
            rails: 4
          - ruby: 3
            rails: 4
          - ruby: 3
            rails: 5

    steps:
    - uses: actions/checkout@master

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: |
        rm -rf Gemfile.lock && bundle && rake
      env:
        RAILS_VERSION: ~> ${{ matrix.rails }}
        DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres?pool=5
